const {
	REACT_APP_API_URL,
	REACT_APP_SERVICE_ID,
	REACT_APP_TEMPLATE_ID,
	REACT_APP_PUBLIC_KEY,
} = process.env;

export {
	REACT_APP_API_URL,
	REACT_APP_SERVICE_ID,
	REACT_APP_TEMPLATE_ID,
	REACT_APP_PUBLIC_KEY,
};
